- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /home/qbittorrent/downloads
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
