- id: cleaning_timer_weekdays
  alias: Takarítás ütemezése hétköznap
  trigger:
  - platform: template
    value_template: '{{ states.sensor.vacuum_start_time_weekdays.state == states.sensor.time.state
      }}'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
- id: cleaning_timer_weekend
  alias: Takarítás ütemezése hétvégén
  trigger:
  - platform: template
    value_template: '{{ states.sensor.vacuum_start_time_weekend.state == states.sensor.time.state
      }}'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.start
