title: 'Home'
views:
  - title: 'home'
    icon: mdi:home
    path: 'home'
    cards: !include_dir_merge_list cards/home
  - title: 'home'
    icon: mdi:chart-bar
    path: 'stats'
    cards: !include_dir_merge_list cards/stats
