title: 'Home'
resources:
  - url: /local/vendor/lovelace-card-tools/card-tools.js?version=0.4
    type: js
  - url: /local/vendor/lovelace-popup-card/popup-card.js?commit=044b089
    type: js
views:
  - title: 'Home'
    icon: mdi:home
    path: 'home'
    cards: !include_dir_merge_list cards/home
  - title: 'Stats'
    icon: mdi:chart-bar
    path: 'stats'
    cards: !include_dir_merge_list cards/stats
