title: 'Home'
resources:
  - url: /local/vendor/lovelace-card-tools/card-tools.js?commit=c885db9
    type: js
  - url: /local/vendor/lovelace-popup-card/popup-card.js?commit=78d39ab
    type: js
views:
  - title: 'Home'
    icon: mdi:home
    path: 'home'
    popup_cards: !include_dir_merge_named views/home/popups
    cards: !include_dir_merge_list views/home/cards
  - title: 'Stats'
    icon: mdi:chart-bar
    path: 'stats'
    cards: !include_dir_merge_list views/stats/cards
