homeassistant:
  customize:

mikrotik:
  - host: !secret mikrotik_ip
    username: !secret mikrotik_username
    password: !secret mikrotik_password
    port: !secret mikrotik_port
    ssl: true
    track_devices: true
