- platform: template
  sensors:
    vacuum_start_time_weekdays:
      friendly_name: 'Takarítás indítási idő (Hétköznap)'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekdays") | int, states("input_number.vacuum_start_minutes_weekdays") | int) }}'
    vacuum_start_time_weekend:
      friendly_name: 'Takarítás indítási idő (Hétvége)'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekend") | int, states("input_number.vacuum_start_minutes_weekend") | int) }}'
    vacuum_status:
      friendly_name: "Vacuum - Status"
      value_template: "Állapot: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"
    vacuum_weekdays:
      friendly_name: "Vacuum - Weekdays"
      value_template: "Hétköznap:"
    vacuum_weekend:
      friendly_name: "Vacuum - Weekend"
      value_template: "Hétvége:"
    vacuum_battery:
      friendly_name: "Vacuum - Battery"
      value_template: "Akku: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}"
      device_class: battery
      unit_of_measurement: '%'
    vacuum_accessories:
      friendly_name: "Vacuum - Kellékek"
      value_template: "KELLÉKEK ÁLLAPOTA"
    vacuum_operation:
      friendly_name: "Vacuum - Üzemelés"
      value_template: "ÜZEMELÉS"
    vacuum_main_brush:
      friendly_name: "Vacuum - Fő kefe"
      value_template: "Fő kefe: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }} h"
    vacuum_side_brush:
      friendly_name: "Vacuum - Első kefe"
      value_template: "Első kefe: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }} h"
    vacuum_filter:
      friendly_name: "Vacuum - Filter"
      value_template: "Filter: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }} h"
    vacuum_sensor:
      friendly_name: "Vacuum - Szenzorok"
      value_template: "Szenzorok: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }} h"
