automation:
  - id: cleaning_schedule_weekdays
    alias: Cleaning Schedule Weekdays
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: '{{ states.sensor.vacuum_start_time_weekdays.state == states.sensor.time.state }}'
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
    - data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
      service: vacuum.start

  - id: cleaning_schedule_weekend
    alias: Cleaning Schedule Weekend
    initial_state: 'false'
    trigger:
    - platform: template
      value_template: '{{ states.sensor.vacuum_start_time_weekend.state == states.sensor.time.state }}'
    condition:
    - condition: time
      weekday:
      - sat
      - sun
    action:
    - data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
      service: vacuum.start

  - id: cleaning_state_changed
    alias: Cleaning State Changed
    initial_state: 'true'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: sensor.vacuum_status
    action:
    - service: notify.mobile_app_redmi_3
      data_template:
        message: "The vacuum is {{ states('sensor.vacuum_activity') }} now."
      data:
        title: 'Xiaomi Vacuum'
        data:
          apns_headers:
            'apns-collapse-id': 'xiaomi-vacuum-state'

  - id: maintenance_needed
    alias: Maintenance needed
    initial_state: 'true'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: device_tracker.redmi
      from: 'not_home'
      to: 'home'
    condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ (state_attr('vacuum.xiaomi_vacuum_cleaner', 'main_brush_left')|int) < 20 }}"
        - condition: template
          value_template: "{{ (state_attr('vacuum.xiaomi_vacuum_cleaner', 'side_brush_left')|int) < 20 }}"
        - condition: template
          value_template: "{{ (state_attr('vacuum.xiaomi_vacuum_cleaner', 'filter_left')|int) < 20 }}"
        - condition: template
          value_template: "{{ (state_attr('vacuum.xiaomi_vacuum_cleaner', 'sensor_dirty_left')|int) < 4 }}"
    action:
    - service: notify.mobile_app_redmi_3
      data:
        title: 'Xiaomi Vacuum'
        message: "The vacuum needs maintenance"
        data:
          apns_headers:
            'apns-collapse-id': 'xiaomi-vacuum-maintenance'
