homeassistant:
  customize:

automation:
  - id: cleaning_schedule_weekdays
    alias: Cleaning Schedule Weekdays
    initial_state: 'true'
    trigger:
    - platform: template
      value_template: '{{ states.sensor.vacuum_start_time_weekdays.state == states.sensor.time.state }}'
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
    - data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
      service: vacuum.start
  - id: cleaning_schedule_weekend
    alias: Cleaning Schedule Weekend
    initial_state: 'false'
    trigger:
    - platform: template
      value_template: '{{ states.sensor.vacuum_start_time_weekend.state == states.sensor.time.state }}'
    condition:
    - condition: time
      weekday:
      - sat
      - sun
    action:
    - data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
      service: vacuum.start
  - id: cleaning_state_changed
    alias: Cleaning State Changed
    initial_state: 'true'
    hide_entity: true
    trigger:
    - platform: state
      entity_id: sensor.vacuum_status
    action:
    - service: notify.push
      data_template:
        message: "The vacuum is {{ states('vacuum.xiaomi_vacuum_cleaner') }} now."
      data:
        title: 'Xiaomi Vacuum'
        data:
          renotify: true
          tag: 'xiaomi-vacuum'

input_number:
  vacuum_start_minutes_weekend:
    name: Start minutes
    initial: 0
    min: 0
    max: 59
    step: 1
    mode: slider
  vacuum_start_hour_weekend:
    name: Start hour
    initial: 13
    min: 0
    max: 23
    step: 1
    mode: slider
  vacuum_start_minutes_weekdays:
    name: Start minutes
    initial: 0
    min: 0
    max: 59
    step: 1
    mode: slider
  vacuum_start_hour_weekdays:
    name: Start hour
    initial: 10
    min: 0
    max: 23
    step: 1
    mode: slider

sensor:
  - platform: template
    sensors:
      vacuum_floorplan:
        friendly_name: 'Floor plan'
        value_template: 'Floor plan'
        icon_template: 'mdi:floor-plan'
      vacuum_maintenance:
        friendly_name: 'Vacuum maintenance'
        value_template: 'Maintenance'
        icon_template: mdi:wrench
      vacuum_start_time_weekdays:
        friendly_name: 'Cleaning Shedule on Weekdays'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekdays") | int, states("input_number.vacuum_start_minutes_weekdays") | int) }}'
      vacuum_start_time_weekend:
        friendly_name: 'Cleaning Shedule on Weekends'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.vacuum_start_hour_weekend") | int, states("input_number.vacuum_start_minutes_weekend") | int) }}'
      vacuum_status:
        friendly_name: "Vacuum - Status"
        value_template: "Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}"
      vacuum_weekdays:
        friendly_name: "Vacuum - Weekdays"
        value_template: "Weekdays:"
      vacuum_weekend:
        friendly_name: "Vacuum - Weekend"
        value_template: "Weekends:"
      vacuum_battery:
        friendly_name: "Vacuum - Battery"
        value_template: "Battery: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}"
        device_class: battery
        unit_of_measurement: '%'
      vacuum_main_brush:
        friendly_name: "Vacuum - Main brush"
        value_template: "Main brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }} h"
      vacuum_side_brush:
        friendly_name: "Vacuum - Side brush"
        value_template: "Side brush: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }} h"
      vacuum_filter:
        friendly_name: "Vacuum - Filter"
        value_template: "Filter: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }} h"
      vacuum_sensor:
        friendly_name: "Vacuum - Sensors"
        value_template: "Sensors: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.sensor_dirty_left }} h"

vacuum:
  - platform: xiaomi_miio
    host: !secret roborock_host
    token: !secret roborock_token
